cidata: move provision scripts to ISO
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

diff --git a/pkg/cidata/cidata.TEMPLATE.d/user-data b/pkg/cidata/cidata.TEMPLATE.d/user-data
--- a/pkg/cidata/cidata.TEMPLATE.d/user-data
+++ b/pkg/cidata/cidata.TEMPLATE.d/user-data
@@ -34,31 +34,26 @@ write_files:
           CODE=1
         fi
       done
+      if [ -d "${LIMA_CIDATA_MNT}"/provision.system ]; then
+        for f in "${LIMA_CIDATA_MNT}"/provision.system/*; do
+          echo "Executing $f"
+          if ! "$f"; then
+            echo "Failed to execute $f"
+            CODE=1
+          fi
+        done
+      fi
+      if [ -d "${LIMA_CIDATA_MNT}"/provision.user ]; then
+        until [ -e "/run/user/{{.UID}}/systemd/private" ]; do sleep 3; done
+        for f in "${LIMA_CIDATA_MNT}"/provision.user/*; do
+          echo "Executing $f (as user {{.User}})"
+          if ! sudo -iu "{{.User}}" "XDG_RUNTIME_DIR=/run/user/{{.UID}}" "$f"; then
+            echo "Failed to execute $f (as user {{.User}})"
+            CODE=1
+          fi
+        done
+      fi
       exit "$CODE"
    owner: root:root
    path: /var/lib/cloud/scripts/per-boot/00-lima.boot.sh
    permissions: '0755'
-{{- if .Provision}}
-# TODO: move Provision scripts to ISO
- - content: |
-      #!/bin/bash
-      set -eu -o pipefail
-      {{- range $i, $val := .Provision}}
-      {{- $script := printf "/var/lib/lima-guestagent/provision-%02d-%s" $i $val.Mode}}
-      {{- if eq $val.Mode "system"}}
-      {{$script}}
-      {{- else}}
-      until [ -e "/run/user/{{.UID}}/systemd/private" ]; do sleep 3; done
-      sudo -iu "{{.User}}" "XDG_RUNTIME_DIR=/run/user/{{.UID}}" {{$script}}
-      {{- end}}
-      {{- end}}
-   owner: root:root
-   path: /var/lib/cloud/scripts/per-boot/50-execute-provision-scripts.boot.sh
-   permissions: '0755'
-{{- end}}
-{{- range $i, $val := .Provision}}
- - content: {{printf "%q" $val.Script}}
-   owner: root:root
-   path: {{printf "/var/lib/lima-guestagent/provision-%02d-%s" $i $val.Mode}}
-   permissions: '0755'
-{{- end}}
